---
title: "Pension Modeling Walkthrough"
author: "A Abbott"
date: "2/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Pension Modeling



```{r echo=FALSE}
library(tidyverse)
library(here)
library(msm)
library(plotly)
library(readxl)
source(here("R", "functions.R"))
```

## Population Generation

Inputs:
- Number of Employees
- Entry Age
- Retirement Age
- Age distribution (median age, standard deviation for use in rtnorm function)
- Mortality table for retirees


```{r population_inputs}
pop_size <- 208244
entry_age <- 20
ret_age <- 65
pop_maturity_type <- 'custom'
mean_age_active <- 45.4
sd_age_active <- 15
mort <- 'RP2014_Employee_total'
max_age <- 100

population_actives <- generate_pop_actives(entry_age = entry_age, ret_age = ret_age, pop_maturity_type = pop_maturity_type, pop_size = pop_size, mean_age_active = mean_age_active, sd_age_active = sd_age_active) 

mort_tab <- switch(
  mort,
  "RP2014_Employee_total" = 2,
  "RP2000_Employee_total" = 4,
  "RP2010_Employee_total" = 6
)

population_retirees <- generate_pop_retirees(entry_age = entry_age, ret_age = ret_age, mort_tab = mort_tab, population_actives = population_actives)

members <- bind_rows(population_actives, population_retirees)
```

```{r ggplot}
ggplot(members, aes(color = population)) +
  geom_histogram(aes(age), binwidth = 5)

```


```{r}
active_count <- read_excel(here('data', 'ASRS_2019_members_count_salary.xlsx'), sheet = 'active_count') %>% 
  filter(`Current Age` != "Total") %>% 
  mutate(age = case_when(
    str_sub(`Current Age`, 1, 2) == 'Un' ~ 20L,
    TRUE ~ as.integer(str_sub(`Current Age`, 1, 2))
  ),
  age = age + 2) %>% 
  select(age, count = Total)

actives <- vector()
j <- 22
max_age = max(active_count$age)
# translating the active count to population for age distribution plot
for (i in active_count$count) {
  actives <- c(actives, rep(j, times = i))
  j = j + 5
  if (j > max_age)
    break
}

actives <- tibble(age = actives, population = 'actives')

# retirees
retiree_count <- read_excel(here('data', 'ASRS_2019_members_count_salary.xlsx'), sheet = 'retiree_count') %>% 
  filter(`Current Age` != "Total") %>% 
  mutate(age = case_when(
    str_sub(`Current Age`, 1, 2) == 'Be' ~ 50L,
    str_sub(`Current Age`, 1, 2) == 'Ov' ~ 95L,
    TRUE ~ as.integer(str_sub(`Current Age`, 1, 2))
  ),
  age = age + 2) %>% 
  select(age, count = Total)

retirees <- vector()
j <- 52
max_age = max(retiree_count$age)
# translating the active count to population for age distribution plot
for (i in retiree_count$count) {
  retirees <- c(retirees, rep(j, times = i))
  j = j + 5
  if (j > max_age)
    break
}

retirees <- tibble(age = retirees, population = 'retirees')

members <- bind_rows(actives, retirees)

ggplot(members, aes(color = population)) +
  geom_histogram(aes(age), binwidth = 5)

```

